version: '2'
services:
    plantatree-app:
        image: plantatree
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://plantatree-postgresql:5432/PlantATree
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    plantatree-postgresql:
        extends:
            file: postgresql.yml
            service: plantatree-postgresql
